# Generated by Django 4.1.4 on 2022-12-18 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название мероприятия')),
                ('event_date', models.DateField(verbose_name='Дата проведения мероприятия')),
                ('post_about_event', models.TextField(verbose_name='Текст поста мероприятия')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='EventStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.event', verbose_name='Мероприятие')),
            ],
            options={
                'verbose_name': 'Стек мероприятия',
                'verbose_name_plural': 'Стеки мероприятий',
            },
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Тип мероприятия',
                'verbose_name_plural': 'Типы мероприятий',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время получения')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название стека технологий')),
            ],
            options={
                'verbose_name': 'Стек технологий',
                'verbose_name_plural': 'Стеки технологий',
            },
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hackathon_subscribe', models.BooleanField(default=True, verbose_name='Подписка на хакатоны')),
                ('lecture_subscribe', models.BooleanField(default=True, verbose_name='Подписка на лекции')),
                ('meet_up_subscribe', models.BooleanField(default=True, verbose_name='Подписка на meet ups')),
                ('vacancy_subscribe', models.BooleanField(default=True, verbose_name='Подписка на вакансии')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'ПОдписки',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('tg_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='telegram id')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя пользователя')),
                ('second_name', models.CharField(max_length=30, verbose_name='Фамилия пользователя')),
                ('birthdate', models.DateTimeField(verbose_name='Дата рождения пользователя')),
                ('about_user', models.TextField(verbose_name='О пользователе')),
                ('telegram_username', models.CharField(max_length=50, unique=True, verbose_name='telegram')),
                ('rating', models.IntegerField(default=0, verbose_name='Рейтинг')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.event', verbose_name='Мероприятие')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Посетитель мероприятий',
                'verbose_name_plural': 'Посетители мероприятий',
            },
        ),
        migrations.CreateModel(
            name='UserStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.stack', verbose_name='Стек технологий')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Стек пользователя',
                'verbose_name_plural': 'Стеки пользователей',
            },
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AddField(
            model_name='subscribe',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.user', verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='message',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.user', verbose_name='Профиль'),
        ),
        migrations.AddField(
            model_name='eventstack',
            name='stack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.stack', verbose_name='Стек технологий'),
        ),
        migrations.AddField(
            model_name='event',
            name='type_of_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.eventtype', verbose_name='Тип мероприятия'),
        ),
    ]
