# Generated by Django 4.1.4 on 2022-12-18 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_user_birthdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribe',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
    ]
