# Generated by Django 4.1.4 on 2022-12-18 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_remove_eventstack_stack_remove_userstack_stack_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventstack',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userstack',
            options={},
        ),
        migrations.AddField(
            model_name='event',
            name='stacks',
            field=models.ManyToManyField(to='web.stack'),
        ),
        migrations.AddField(
            model_name='user',
            name='stacks',
            field=models.ManyToManyField(to='web.stack'),
        ),
    ]
