version: '3.8'

services:
  web:
    build: ./admin
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./admin/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./admin/.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=django_user
      - POSTGRES_PASSWORD=django_password
      - POSTGRES_DB=django_db
  bot:
    build: ./bot
    command: python bot.py
    env_file: 
      - ./bot/.env
    volumes:
      - ./bot/:/usr/src/app/
    depends_on:
      - db
      - web



volumes:
  postgres_volume:
