version: '3.3'

services:
  bot:
    image: "${BOT_IMAGE_NAME:-tg_bot-image}"
    container_name: "${BOT_CONTAINER_NAME:-tg_bot-container}"
    stop_signal: SIGINT
    build:
      context: ./bot
    working_dir: "/usr/src/app/${BOT_NAME:-tg_bot}"
    volumes:
    - .:/usr/src/app/${BOT_NAME:-tg_bot}
    # command: python3 -m ./bot/bot
    restart: always
    env_file:
      - "./bot/.env"
    networks:
    - tg_bot
  django:
       build: ./admin
       command: python3 manage.py runserver localhost:8000
       ports:
           - 8000:8000


networks:
  tg_bot:
    driver: bridge
