# Generated by Django 4.1.4 on 2022-12-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_message_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='about_user',
            field=models.TextField(null=True, verbose_name='О пользователе'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(null=True, verbose_name='Дата рождения пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30, null=True, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='second_name',
            field=models.CharField(max_length=30, null=True, verbose_name='Фамилия пользователя'),
        ),
    ]
