# Generated by Django 4.1.4 on 2022-12-19 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_alter_user_about_user_alter_user_birthdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='title',
            field=models.CharField(max_length=50, unique=True, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='stack',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название стека технологий'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.user', unique=True, verbose_name='Пользователь'),
        ),
    ]
